# Generated by Django 5.1.1 on 2024-12-07 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_paymenttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='merchant_request_id',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='received_at',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='result_code',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='result_description',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='checkout_request_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
