# Generated by Django 5.1.1 on 2024-12-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_paymenttransaction_merchant_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='phone_number',
            field=models.CharField(default=254, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='result_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='checkout_request_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
